"""creacion de la base de datos Diskyoval

Revision ID: 760194d395da
Revises: 
Create Date: 2024-10-13 15:09:18.555861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760194d395da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id_client', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('email')
    )
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_product')
    )
    op.create_table('cart',
    sa.Column('id_cart', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ),
    sa.PrimaryKeyConstraint('id_cart')
    )
    op.create_table('product_cart',
    sa.Column('id_product_cart', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cart', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('reserved_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cart'], ['cart.id_cart'], ),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.PrimaryKeyConstraint('id_product_cart')
    )
    op.create_table('transactions',
    sa.Column('id_transaction', sa.Integer(), nullable=False),
    sa.Column('id_cart', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_cart'], ['cart.id_cart'], ),
    sa.PrimaryKeyConstraint('id_transaction')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('product_cart')
    op.drop_table('cart')
    op.drop_table('products')
    op.drop_table('clients')
    # ### end Alembic commands ###
